SET (CTEST_SOURCE_DIRECTORY "$ENV{HOME}/build/nightly/src/plastimatch")
SET (CTEST_BINARY_DIRECTORY "$ENV{HOME}/build/nightly/tempest_01/plastimatch")
SET (CTEST_CMAKE_COMMAND "/usr/bin/cmake -Wno-dev")
SET (CTEST_COMMAND "/usr/bin/ctest -D Nightly")
SET (CTEST_INITIAL_CACHE "
//Name of generator.
CMAKE_GENERATOR:INTERNAL=Unix Makefiles

//Name of the build
//BUILDNAME:STRING=osx10.7.3-Pisr-Cd-gcc4.2-cuda4.1
BUILDNAME:STRING=x01-osx10.7.3-Pisr-Cd

//Name of the computer/site where compile is being run
SITE:STRING=tempest-gcc4.2-cuda4.1

//Build with shared libraries.
BUILD_SHARED_LIBS:BOOL=OFF

// Use anonymous checkout
SVN_UPDATE_OPTIONS:STRING=--username anonymous --password \\\"\\\"

//Disable REG-2-3
PLM_CONFIG_DISABLE_REG23:BOOL=ON

//Enabled all unit test 
PLM_DOWNLOAD_DICOMRT_33_STRUCT:BOOL=ON
PLM_DOWNLOAD_DICOMRT_AW:BOOL=ON
PLM_DOWNLOAD_DICOMRT_CERR:BOOL=ON
PLM_DOWNLOAD_DICOMRT_CORVUS:BOOL=ON
PLM_DOWNLOAD_DICOMRT_IRREGULAR:BOOL=ON
PLM_DOWNLOAD_DICOMRT_PINNACLE:BOOL=ON
PLM_DOWNLOAD_DICOMRT_XIO:BOOL=ON
PLM_DOWNLOAD_FDK_VARIAN:BOOL=ON
PLM_DOWNLOAD_HEADPHANTOM:BOOL=ON
PLM_DOWNLOAD_RTOG_CORVUS:BOOL=ON
PLM_DOWNLOAD_XIO:BOOL=ON
")
