SET (CTEST_SOURCE_DIRECTORY "$ENV{HOME}/src/plastimatch-continuous")
SET (CTEST_BINARY_DIRECTORY "$ENV{HOME}/build/plastimatch-continuous")
SET (CTEST_CMAKE_COMMAND "/usr/bin/cmake -Wno-dev")
SET (CTEST_COMMAND "/usr/bin/ctest -D Continuous")
SET (CTEST_INITIAL_CACHE "
//Name of generator.
CMAKE_GENERATOR:INTERNAL=Unix Makefiles

//Name of the build
BUILDNAME:STRING=osx10.7.3-Pisr-Cd-hourly

//Name of the computer/site where compile is being run
SITE:STRING=tempest-gcc4.2-cuda5.0

//Build with shared libraries.
BUILD_SHARED_LIBS:BOOL=OFF

//PLM_CONFIG_DISABLE_REG23:BOOL=ON

//Enabled all unit test 
PLM_DOWNLOAD_DICOMRT_33_STRUCT:BOOL=OFF
PLM_DOWNLOAD_DICOMRT_AW:BOOL=OFF
PLM_DOWNLOAD_DICOMRT_CERR:BOOL=OFF
PLM_DOWNLOAD_DICOMRT_CORVUS:BOOL=OFF
PLM_DOWNLOAD_DICOMRT_IRREGULAR:BOOL=OFF
PLM_DOWNLOAD_DICOMRT_PINNACLE:BOOL=OFF
PLM_DOWNLOAD_DICOMRT_XIO:BOOL=OFF
PLM_DOWNLOAD_FDK_VARIAN:BOOL=OFF
PLM_DOWNLOAD_HEADPHANTOM:BOOL=OFF
PLM_DOWNLOAD_RTOG_CORVUS:BOOL=OFF
PLM_DOWNLOAD_XIO:BOOL=OFF
")
