# - Find Sqlite3
# Find the native Sqlite3 includes and library
#
#  SQLITE3_INCLUDE_DIR - where to find zlib.h, etc.
#  SQLITE3_LIBRARIES   - List of libraries when using zlib.
#  SQLITE3_FOUND       - True if zlib found.


IF (SQLITE3_INCLUDE_DIR)
  # Already in cache, be silent
  SET (SQLite3_FIND_QUIETLY TRUE)
ENDIF (SQLITE3_INCLUDE_DIR)

FIND_PATH(SQLITE3_INCLUDE_DIR sqlite3.h)

SET (SQLITE3_NAMES sqlite3)
FIND_LIBRARY (SQLITE3_LIBRARY NAMES ${SQLITE3_NAMES})

# handle the QUIETLY and REQUIRED arguments and set SQLITE3_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE (FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS (SQLite3 DEFAULT_MSG 
  SQLITE3_LIBRARY 
  SQLITE3_INCLUDE_DIR)

IF (SQLITE3_FOUND)
  SET (SQLITE3_LIBRARIES ${SQLITE3_LIBRARY})
ELSE (SQLITE3_FOUND)
  SET (SQLITE3_LIBRARIES)
ENDIF (SQLITE3_FOUND)

MARK_AS_ADVANCED (SQLITE3_LIBRARY SQLITE3_INCLUDE_DIR)
