# - find PANTHEIOS libraries
#

#  STLSOFT_INCLUDE_DIR     - Include directories for STLSOFT
#  PANTHEIOS_INCLUDE_DIR   - Include directories for PANTHEIOS
#  PANTHEIOS_FOUND         - If false, don't try to use PANTHEIOS

FIND_PATH(PANTHEIOS_INCLUDE_DIR pantheios/pantheios.h
	$ENV{FASTFORMAT_ROOT}/include
	)

FIND_PATH(STLSOFT_INCLUDE_DIR stlsoft/algorithms.hpp
	$ENV{STLSOFT}/include
	)

IF(PANTHEIOS_INCLUDE_DIR AND STLSOFT_INCLUDE_DIR)
  SET(PANTHEIOS_FOUND TRUE)
ELSE(PANTHEIOS_INCLUDE_DIR AND STLSOFT_INCLUDE_DIR)
  SET(PANTHEIOS_FOUND FALSE)
ENDIF(PANTHEIOS_INCLUDE_DIR AND STLSOFT_INCLUDE_DIR)
