
%% Make mexwncc
clear mexwncc;
mex -v ...
    ../source/mexwncc.cpp ...
    ../source/mexutils.cpp ...
    ../source/scorewin.cpp ...
    ../source/s_wncc.cpp ...
    ../source/image.cpp;

return;

%% Make mexgpyr_img
clear mexgpyr_img;
mex -v ...
    ../source/mexgpyr_img.cpp ...
    ../source/mexutils.cpp ...
    ../source/image.cpp;

%% Make mexgpyr_free
clear mexgpyr_free;
mex -v ...
    ../source/mexgpyr_free.cpp ...
    ../source/mexutils.cpp ...
    ../source/image.cpp;

%% Make mexgpyr
clear mexgpyr;
mex -v ...
    ../source/mexgpyr.cpp ...
    ../source/mexutils.cpp ...
    ../source/gpyr.cpp ...
    ../source/image.cpp;

return;

%% Test code
testgpyr;
testwncc;
