## This script compares a value in a text file against lower and 
##   upper thresholds

MESSAGE (STATUS "INFILE is ${INFILE}")
MESSAGE (STATUS "REGEX is ${REGEX}")
MESSAGE (STATUS "LOWER_THRESH is ${LOWER_THRESH}")
MESSAGE (STATUS "UPPER_THRESH is ${UPPER_THRESH}")

FILE (STRINGS ${INFILE} TEST_OUTPUT REGEX ${REGEX})
MESSAGE(STATUS "PARSED VALUE=|${TEST_OUTPUT}|")

STRING (REGEX MATCH ${REGEX} TEST_OUTPUT ${TEST_OUTPUT})
SET (TEST_OUTPUT ${CMAKE_MATCH_1})
MESSAGE(STATUS "PARSED_VALUE=|${TEST_OUTPUT}|")

IF (CMAKE_MATCH_1 GREATER ${LOWER_THRESH} 
    AND CMAKE_MATCH_1 LESS ${UPPER_THRESH})
  MESSAGE("Not an error")
ELSE (CMAKE_MATCH_1 GREATER ${LOWER_THRESH} 
    AND CMAKE_MATCH_1 LESS ${UPPER_THRESH})
  MESSAGE(SEND_ERROR "An error")
ENDIF (CMAKE_MATCH_1 GREATER ${LOWER_THRESH} 
  AND CMAKE_MATCH_1 LESS ${UPPER_THRESH})
