
#ifndef ORAQPROGRESSEMITTER_H_
#define ORAQPROGRESSEMITTER_H_


#include "oraQVTKProgressEventAdaptor.h"


namespace ora
{


/** \class QProgressEmitter
 * \brief Is capable of emitting arbitrary progress signals from any class.
 *
 * This class is an extension of QVTKProgressEventAdaptor and does not need
 * a VTK object for generating progress signals. Progress signals with
 * arbitrary progress values can be generated by simply invoking the
 * SetProgress() method from any class.
 *
 * \sa QVTKProgressEventAdaptor
 *
 * @author phil 
 * @version 1.0
 */
class QProgressEmitter
  : public QVTKProgressEventAdaptor
{

Q_OBJECT

public:
  /** Default constructor **/
  QProgressEmitter();
  /** Destructor **/
  virtual ~QProgressEmitter();

  /**
   * Emit a progress signal with the specified value.
   * @param progress the progress value
   **/
  virtual void SetProgress(double progress);

};


}


#endif /* ORAQPROGRESSEMITTER_H_ */
