# Bitflow lib and include path
# These variables are set:
#
#   HAVE_BITFLOW
#   BITFLOW_FOUND
#   BITFLOW_INCLUDE_DIR
#   BITFLOW_LIBRARIES
#
# Only works on Windows

SET(BITFLOW_FOUND FALSE)
IF(WIN32)
  FIND_PATH(BITFLOW_ROOT_DIR "include/BFApi.h"
    "C:/BitFlow SDK 4.00"
    )
  SET(BITFLOW_INCLUDE_DIR ${BITFLOW_ROOT_DIR}/include
    DOC "Path to BITFLOW include directory")
  FIND_PATH(BITFLOW_LIBRARY_PATH "BFD.lib"
            ${BITFLOW_ROOT_DIR}/lib
            DOC "Path to BITFLOW libraries.")
  FIND_LIBRARY(BITFLOW_BFD_LIB BFD ${BITFLOW_LIBRARY_PATH})
  FIND_LIBRARY(BITFLOW_R2D_LIB R2d ${BITFLOW_LIBRARY_PATH})
  FIND_LIBRARY(BITFLOW_DISPSURF_LIB DispSurf ${BITFLOW_LIBRARY_PATH})
  IF(BITFLOW_ROOT_DIR)
    SET(BITFLOW_FOUND TRUE)
    SET(BITFLOW_LIBRARIES ${BITFLOW_BFD_LIB} ${BITFLOW_R2D_LIB} ${BITFLOW_DISPSURF_LIB})
  ELSE(BITFLOW_ROOT_DIR)
    SET(BITFLOW_LIBRARIES "")
  ENDIF(BITFLOW_ROOT_DIR)
ENDIF(WIN32)
SET(HAVE_BITFLOW ${BITFLOW_FOUND})
